In [ ]:
import re
import string
import nltk

In [ ]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |  

True

# basic cleaning

In [ ]:
text ='''🚀 Learn AI & ML in 2026 with us! Visit https://www.jeevithaaiacademy.com
 💻✨<div>Get 50% OFF now!!! 💥 #AI #ML @everyone</div>'''

In [ ]:
def clean_text(text):
  text = text.lower()
  # remove html tags
  text = re.sub(r'<.*?>','',text)
  # remove url
  text = re.sub(r'http\S+|www\S+','',text)
  # remove emojis
  text = re.sub(r'[^\x00-\x7F]+','',text)
  # remove special chars
  text = re.sub(r'[^a-z0-9]',' ',text)
  # remove white spaces
  text = re.sub(r'\s+',' ',text).strip()
  return text

In [ ]:
clean_text(text)

'learn ai ml in 2026 with us visit get 50 off now ai ml everyone'

# Tokenization

In [ ]:
from nltk.tokenize import word_tokenize,sent_tokenize
# word tokenization
text = "NLP is very interesting to learn"
words = word_tokenize(text)
[x for x in words]

['NLP', 'is', 'very', 'interesting', 'to', 'learn']

In [ ]:
# Sentence Tokenization
text = 'Python is easy. Sql is hard. I like NLP'
sent = sent_tokenize(text)
[x for x in sent]

['Python is easy.', 'Sql is hard.', 'I like NLP']

# Stop words

In [ ]:
from nltk.corpus import stopwords
stop_words=set(stopwords.words('english'))

In [ ]:
text = "NLP is very interesting to learn"
words = word_tokenize(text)
[x for x in words if x not in stop_words]

['NLP', 'interesting', 'learn']

# Stemming

In [ ]:
from nltk.stem import PorterStemmer
ps= PorterStemmer()

In [ ]:
text = 'playing played plays studies studying better'
words = word_tokenize(text)
[ps.stem(x) for x in words]

['play', 'play', 'play', 'studi', 'studi', 'better']

**Pos Tagging**

In [ ]:
from nltk import pos_tag
text = 'John has started studying NLP and it seems very intersting'
words = word_tokenize(text)
pos_tag(words)

[('John', 'NNP'),
 ('has', 'VBZ'),
 ('started', 'VBN'),
 ('studying', 'VBG'),
 ('NLP', 'NNP'),
 ('and', 'CC'),
 ('it', 'PRP'),
 ('seems', 'VBZ'),
 ('very', 'RB'),
 ('intersting', 'JJ')]

| Word        | Tag | Meaning                       |
| ----------- | --- | ----------------------------- |
| NLP         | NNP | Proper Noun (name of a field) |
| is          | VBZ | Verb (3rd person singular)    |
| very        | RB  | Adverb                        |
| interesting | JJ  | Adjective                     |
| and         | CC  | Conjunction                   |
| easy        | JJ  | Adjective                     |
| to          | TO  | "to" (infinitive marker)      |
| implement   | VB  | Base form Verb                |


**Lemmetization**

In [ ]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
le = WordNetLemmatizer()
text = 'playing played plays studies studying better'


In [ ]:
le.lemmatize('studying',pos=wordnet.VERB)

'study'

In [ ]:
le.lemmatize('studies')

'study'

In [ ]:
le.lemmatize('playing',pos=wordnet.VERB)

'play'

In [ ]:
le.lemmatize('better',pos= wordnet.ADJ)

'good'

**Named Entity recognition**

In [ ]:
from nltk import ne_chunk
text = 'John is working at Apple company in Bengaluru'
words=word_tokenize(text)
tag = pos_tag(words)
ner = ne_chunk(tag)
print(ner)

(S
  (PERSON John/NNP)
  is/VBZ
  working/VBG
  at/IN
  (ORGANIZATION Apple/NNP)
  company/NN
  in/IN
  (GPE Bengaluru/NNP))


**Bag of words(BOW)**

In [ ]:
# countvectorizer
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
text = ['Python is easy , python is hard']
x = cv.fit_transform(text)

In [ ]:
cv.get_feature_names_out()

array(['easy', 'hard', 'is', 'python'], dtype=object)

In [ ]:
x.toarray()

array([[1, 1, 2, 2]])

In [ ]:
# countvectorizer
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
text = ['Python is easy' , 'python is hard']
x = cv.fit_transform(text)

In [ ]:
cv.get_feature_names_out()

array(['easy', 'hard', 'is', 'python'], dtype=object)

In [ ]:
x.toarray()

array([[1, 0, 1, 1],
       [0, 1, 1, 1]])

**N-grams**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,1))#unigram
text = ['Python is easy python is hard']
x = cv.fit_transform(text)

In [ ]:
cv.get_feature_names_out()

array(['easy', 'hard', 'is', 'python'], dtype=object)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))#bigram
text = ['Python is easy,python is hard']
x = cv.fit_transform(text)

In [ ]:
cv.get_feature_names_out()

array(['easy python', 'is easy', 'is hard', 'python is'], dtype=object)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))#trigram
text = ['Python is easy,python is hard']
x = cv.fit_transform(text)

In [ ]:
cv.get_feature_names_out()

array(['easy python is', 'is easy python', 'python is easy',
       'python is hard'], dtype=object)

**TF-IDF**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
text = ['Python is easy','python is hard']

In [ ]:
x = tf.fit_transform(text)

In [ ]:
x.toarray()

array([[0.70490949, 0.        , 0.50154891, 0.50154891],
       [0.        , 0.70490949, 0.50154891, 0.50154891]])

In [ ]:
tf.get_feature_names_out()

array(['easy', 'hard', 'is', 'python'], dtype=object)

# Spacy

In [ ]:
!pip install spacy gensim scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 56.7 MB/s eta 0:00:00


In [ ]:
!python -m spacy download en_core_web_sm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 36.9 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [ ]:
import spacy
model = spacy.load('en_core_web_sm')

**Word Tokenization**

In [ ]:
text = 'I like NLP'
words = model(text)
[x.text for x in words]

['I', 'like', 'NLP']

**Sentence Tokenization**

In [ ]:
text = 'python is easy. Sql is hard'
sentence = model(text)
[x.text for x in sentence.sents]


['python is easy.', 'Sql is hard']

**Stop words**


In [ ]:
text = 'python is easy Sql is hard'
words = model(text)
[x.text for x in words if not x.is_stop]

['python', 'easy', 'Sql', 'hard']

# lemmatization

In [ ]:
text = 'playing played plays studies studying better'
words = model(text)
[x.lemma_ for x in words]

['play', 'play', 'play', 'study', 'study', 'well']

# Pos tag

In [ ]:
text = 'John has started studying NLP and it seems very intersting'
words = model(text)
{x:x.pos_ for x in words if not x.is_stop}

{John: 'PROPN',
 started: 'VERB',
 studying: 'VERB',
 NLP: 'PROPN',
 intersting: 'VERB'}

# NER

In [ ]:
text = 'John is working at Apple company in Bengaluru'
words = model(text)
{x:x.label_ for x in words.ents}

{John: 'PERSON', Apple: 'ORG', Bengaluru: 'GPE'}

In [ ]:
#Break till 5pm